name: Terraform e Deploy Kubernetes

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configura o Azure CLI
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Configura Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.9.6'

      - name: Inicializa Terraform
        run: terraform -chdir=Terraform/ init

      - name: Formata Terraform
        run: terraform -chdir=Terraform/ fmt -check

      - name: Valida Terraform
        run: terraform -chdir=Terraform/ validate

      # Está levando mais de 25 minutos e não está completando
      - name: Planeja Terraform
        run: terraform -chdir=Terraform/ plan -out=tfplan

      - name: Aplica Terraform
        run: terraform -chdir=Terraform/ apply -auto-approve tfplan
        # run: terraform -chdir=Terraform/ apply -auto-approve

      # - name: Set Azure subscription
      #   run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: Output Terraform
      #   run: terraform -chdir=Terraform/ output -json
      #   env:
      #     TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  # kubernetes:
  #   needs: terraform
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout do Repositório
  #       uses: actions/checkout@v4

  #     - name: Configurar kubectl
  #       uses: azure/setup-kubectl@v3
  #       with:
  #         version: 'latest'

  #     - name: Configurar Azure Credentials
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}

  #     - name: Substituir Placeholders nos ConfigMaps
  #       env:
  #         POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  #         POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  #         DATABASE_URL: ${{ secrets.DATABASE_URL }}
  #       run: |
  #         envsubst < K8S/db/configMap.yml > K8S/db/configMap_temp.yml
  #         envsubst < K8S/app/configMap.yml > K8S/app/configMap_temp.yml

  #     - name: Aplicar ConfigMaps no Kubernetes
  #       run: |
  #         kubectl apply -f K8S/db/configMap_temp.yml
  #         kubectl apply -f K8S/app/configMap_temp.yml

  #     - name: Limpar Arquivos Temporários
  #       run: |
  #         rm K8S/db/configMap_temp.yml
  #         rm K8S/app/configMap_temp.yml
